import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Slack, Copy, ExternalLink } from 'lucide-react';
import { useState } from 'react';
import { emitter } from '@/agentSdk';

interface SlackPreviewProps {
    summary: string[];
    onConnectSlack: () => void;
    isConnected?: boolean;
}

export const SlackPreview = ({ summary, onConnectSlack, isConnected = false }: SlackPreviewProps) => {
    const [copied, setCopied] = useState(false);
    const [sending, setSending] = useState(false);

    const slackFormattedMessage = summary.join('\n');

    const handleCopyMessage = async () => {
        try {
            await navigator.clipboard.writeText(slackFormattedMessage);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (error) {
            console.error('Failed to copy message:', error);
        }
    };

    const handleSendToSlack = async () => {
        setSending(true);
        try {
            await emitter.emit({
                agentId: '90d76718-973e-4519-bfde-f182d01d45a0',
                event: 'sendSummaryToSlack',
                payload: {
                    summary: slackFormattedMessage,
                    recipient: 'Sagar Jadhav',
                    bulletPoints: summary
                }
            });
            // Call the original onConnectSlack for any additional UI updates
            onConnectSlack();
        } catch (error) {
            console.error('Failed to send to Slack:', error);
        } finally {
            setSending(false);
        }
    };

    return (
        <Card className='bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-950/20 dark:to-indigo-950/20 border-blue-200 dark:border-blue-800'>
            <CardHeader className='flex flex-row items-center justify-between space-y-0 pb-4'>
                <div className='flex items-center gap-2'>
                    <Slack className='h-5 w-5 text-blue-600' />
                    <CardTitle className='text-lg font-semibold'>Slack Message Preview & Send</CardTitle>
                </div>
                <Badge
                    variant='outline'
                    className='bg-blue-100 text-blue-700 border-blue-300'
                >
                    Ready to send
                </Badge>
            </CardHeader>
            <CardContent className='space-y-4'>
                <div className='bg-white dark:bg-gray-900 border rounded-lg p-4 space-y-2'>
                    <div className='flex items-center gap-2 mb-2'>
                        <div className='w-6 h-6 bg-blue-600 rounded flex items-center justify-center'>
                            <span className='text-white text-xs font-bold'>🤖</span>
                        </div>
                        <span className='text-sm font-medium'>Q3 Marketing Strategy focus on digital channels.</span>
                    </div>
                    {summary.map((point, index) => (
                        <div
                            key={index}
                            className='text-sm text-gray-700 dark:text-gray-300 pl-8'
                        >
                            {point.replace(/^•\s*/, '• ')}
                        </div>
                    ))}
                    <div className='text-xs text-gray-500 dark:text-gray-400 pt-2 border-t'>
                        <span>✨ Generated by AI Slack Summarizer</span>
                    </div>
                </div>

                <div className='flex flex-col sm:flex-row gap-2'>
                    <Button
                        onClick={handleSendToSlack}
                        className='flex items-center gap-2 bg-blue-600 hover:bg-blue-700'
                        disabled={sending}
                    >
                        <ExternalLink className='h-4 w-4' />
                        {sending ? 'Sending...' : 'Connect & Send to Slack'}
                    </Button>
                    <Button
                        variant='outline'
                        onClick={handleCopyMessage}
                        className='flex items-center gap-2'
                    >
                        <Copy className='h-4 w-4' />
                        {copied ? 'Copied Message' : 'Copy Message'}
                    </Button>
                </div>

                <p className='text-xs text-muted-foreground'>
                    * Click "Connect & Send to Slack" to send this summary directly to Sagar Jadhav via Slack.
                </p>
            </CardContent>
        </Card>
    );
};
